-- +goose Up
-- ============================================================================
-- EMISSIONS MONITORING PLATFORM -- COMPLETE SCHEMA
-- ============================================================================
--
-- A multi-tenant platform that ingests emission readings from field devices,
-- sensors, and satellites; rolls them up into per-period aggregates; and
-- detects when an org / site / asset exceeds its configured emission policy.
--
-- CONTENTS
--   Section 1  Core hierarchy        organizations, sites, asset_types, assets
--   Section 2  People & devices      users, recorder_devices, user_recorder_devices
--   Section 3  Readings              asset_emission_readings (+ partitions)
--   Section 4  Policies              emission_policies
--   Section 5  Rollup tables         emission_rollup_{hourly,daily,monthly}
--   Section 6  Violations            emission_violations
--   Section 7  The job               refresh_emissions() -- rollup + violation scan
--   Section 8  Read-side views
--
-- DESIGN PRINCIPLES
--   * The whole emissions side is addressed uniformly as
--         (org_id, entity_type, entity_id)   entity_type IN ('org','site','asset')
--   * Composite foreign keys enforce hierarchy integrity -- a child can never
--     reference a parent belonging to a different org/site.
--   * Readings are append-only. This makes bucket totals monotonic and a
--     calendar-period breach permanent -- the whole rollup/violation design
--     depends on it (see Section 10).
--   * UUIDs are generated by the database (the application does not supply id).
--
-- POSTGRES VERSION NOTES
--   gen_random_uuid() is built in (PG13+). btree_gist is required for the
--   exclusion constraints. uuidv7() is built in only on PG18+ (see Section 3).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- needed for EXCLUDE constraints


-- ============================================================================
-- SECTION 1 -- CORE HIERARCHY
-- ============================================================================
-- org -> site -> asset. Each level sums into the one above it.

CREATE TABLE organizations (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT        NOT NULL,
    description     TEXT,
    office_location TEXT,
    email           TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ                       -- soft delete
);

-- Email is logically unique and a natural lookup key (auth, org resolution).
CREATE UNIQUE INDEX idx_organizations_email
    ON organizations (email);

-- Most queries filter to active orgs; a partial index stays small by
-- indexing only non-deleted rows.
CREATE INDEX idx_organizations_active
    ON organizations (id)
    WHERE deleted_at IS NULL;


-- A static lookup table. A separate table (vs a CHECK enum) lets new types be
-- added without a migration, and lets a type carry metadata later.
CREATE TABLE asset_types (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT        NOT NULL UNIQUE,   -- 'compressor', 'tank', ...
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE sites (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id     UUID        NOT NULL REFERENCES organizations(id),
    name       TEXT        NOT NULL,
    location   TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    -- NOT for queries: this exists so child tables (assets, readings) can hold
    -- a COMPOSITE foreign key (org_id, site_id). That composite FK is what
    -- guarantees a site cannot be paired with the wrong org.
    UNIQUE (org_id, id)
);

-- Dominant query: "active sites for this org" (dashboards, dropdowns).
CREATE INDEX idx_sites_org
    ON sites (org_id)
    WHERE deleted_at IS NULL;


CREATE TABLE assets (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID        NOT NULL,
    site_id       UUID        NOT NULL,
    asset_type_id UUID        REFERENCES asset_types(id),
    name          TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,

    -- Composite FK: validates (org_id, site_id) as a PAIR -- the asset's site
    -- must belong to the asset's org. Two independent FKs would not catch a
    -- mismatched pairing.
    FOREIGN KEY (org_id, site_id) REFERENCES sites (org_id, id),

    -- Composite FK target for asset_emission_readings (org_id, site_id, asset_id).
    UNIQUE (org_id, site_id, id)
);

-- One composite index serves three query shapes via the left-prefix rule:
--   (org_id)                          -> all active assets in an org
--   (org_id, site_id)                 -> all active assets in a site
--   (org_id, site_id, asset_type_id)  -> e.g. all active compressors in a site
-- A separate (org_id, site_id) index would be redundant -- this one covers it.
CREATE INDEX idx_assets_org_site_type
    ON assets (org_id, site_id, asset_type_id)
    WHERE deleted_at IS NULL;


-- ============================================================================
-- SECTION 2 -- PEOPLE & DEVICES
-- ============================================================================

-- Contractor engineers. Global -- NOT scoped to an org. Their association with
-- an org is derived through the readings they produce.
CREATE TABLE users (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT        NOT NULL,
    last_name  TEXT        NOT NULL,
    email      TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- Partial UNIQUE index (not an inline UNIQUE constraint): uniqueness applies
-- only to active users, so a deleted user's email can be reclaimed.
CREATE UNIQUE INDEX idx_users_email_active
    ON users (email)
    WHERE deleted_at IS NULL;


-- The source of every reading. Three types with different ownership:
--   field_device -- global, carried by engineers      -> org_id MUST be NULL
--   sensor       -- org-scoped automated source        -> org_id MUST be set
--   satellite    -- org-scoped automated source        -> org_id MUST be set
CREATE TABLE recorder_devices (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID        REFERENCES organizations(id),
    type            TEXT        NOT NULL CHECK (type IN ('field_device','sensor','satellite')),
    device_metadata JSONB,      -- shape varies by type -> JSONB avoids many nullable cols
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,

    -- Enforce the ownership rule at the DB level -- it is a hard invariant.
    CONSTRAINT recorder_devices_org_scope_check CHECK (
        (type = 'field_device' AND org_id IS NULL)
        OR (type IN ('sensor','satellite') AND org_id IS NOT NULL)
    )
);

-- "Active sensors/satellites for this org", and "of a given type" via prefix.
-- Excludes field devices automatically (they have org_id IS NULL).
CREATE INDEX idx_recorder_devices_org_type
    ON recorder_devices (org_id, type)
    WHERE deleted_at IS NULL AND org_id IS NOT NULL;


-- Assignment history: which engineer held which field device, and when.
-- assigned_during is a range: [issued, revoked) -- upper bound NULL = open.
CREATE TABLE user_recorder_devices (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID        NOT NULL REFERENCES users(id),
    recorder_device_id UUID        NOT NULL REFERENCES recorder_devices(id),
    assigned_during    TSTZRANGE   NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- No two assignments for the same device may overlap in time. Forces the
    -- close-then-open pattern and makes "who held device X at time T" an
    -- unambiguous lookup. Backed by a GIST index that also SERVES that lookup
    -- (recorder_device_id =, assigned_during @> T) -- no separate index needed.
    EXCLUDE USING GIST (
        recorder_device_id WITH =,
        assigned_during    WITH &&
    )
);

-- Reverse lookup: "which devices has this engineer held" (the exclusion
-- constraint's index leads with recorder_device_id, so it can't serve this).
CREATE INDEX idx_user_recorder_devices_user
    ON user_recorder_devices (user_id);


-- ============================================================================
-- SECTION 3 -- READINGS  (the highest-volume table)
-- ============================================================================
-- Append-only. Partitioned by recorded_at so time-windowed queries prune to
-- recent partitions and old data can be dropped instantly.

CREATE TABLE asset_emission_readings (
    -- DB-generated. NOTE: on PG18+ prefer DEFAULT uuidv7() -- time-ordered
    -- UUIDs append to the index instead of scattering, which materially
    -- reduces fragmentation on this, the highest-write table.
    id                 UUID        NOT NULL DEFAULT gen_random_uuid(),

    org_id             UUID        NOT NULL REFERENCES organizations(id),
    site_id            UUID        NOT NULL,
    asset_id           UUID        NOT NULL,
    recorder_device_id UUID        NOT NULL REFERENCES recorder_devices(id),

    -- Correlation token, not a FK: readings that arrived in one request array
    -- share a batch_id. There is no batch entity to reference.
    batch_id           UUID        NOT NULL,

    reading            NUMERIC     NOT NULL,   -- quantity emitted in the interval
    unit               TEXT        NOT NULL DEFAULT 'kg_co2e',
    recorded_at        TIMESTAMPTZ NOT NULL,   -- when measured (partition key)
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),  -- when inserted

    -- The partition key (recorded_at) must be part of every unique constraint,
    -- so the PK is composite.
    PRIMARY KEY (id, recorded_at),

    -- Single composite FK to assets is sufficient: asset_id is mandatory, and
    -- no asset row can exist without a valid (org_id, site_id) pair -- so this
    -- transitively guarantees the site too. A separate readings->sites FK was
    -- dropped to save one constraint check per insert on the hottest table.
    FOREIGN KEY (org_id, site_id, asset_id) REFERENCES assets (org_id, site_id, id)
) PARTITION BY RANGE (recorded_at);

-- Hot path: time-range scans scoped down the hierarchy. One composite index
-- covers org / org+site / org+site+asset queries via the left-prefix rule;
-- recorded_at DESC trailing means "most recent N" needs no sort.
CREATE INDEX idx_readings_hierarchy_time
    ON asset_emission_readings (org_id, site_id, asset_id, recorded_at DESC);

-- Device attribution + the join path to user_recorder_devices.
CREATE INDEX idx_readings_device_time
    ON asset_emission_readings (recorder_device_id, recorded_at DESC);

-- Initial monthly partitions. Automate ahead-of-time creation with pg_partman.
CREATE TABLE asset_emission_readings_2026_05 PARTITION OF asset_emission_readings
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE asset_emission_readings_2026_06 PARTITION OF asset_emission_readings
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE asset_emission_readings_2026_07 PARTITION OF asset_emission_readings
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');


-- ============================================================================
-- SECTION 4 -- POLICIES
-- ============================================================================
-- A policy is a time-windowed rule: "this entity may not emit more than
-- emission_limit per `period`". One unified table for all three entity levels
-- (consistent with rollups and violations). Policies are never mutated --
-- they are retired (effective_to) and replaced (see Section 10).

CREATE TABLE emission_policies (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         UUID        NOT NULL REFERENCES organizations(id),

    entity_type    TEXT        NOT NULL CHECK (entity_type IN ('org','site','asset')),
    entity_id      UUID        NOT NULL,

    emission_limit NUMERIC     NOT NULL,
    unit           TEXT        NOT NULL DEFAULT 'kg_co2e',
    period         TEXT        NOT NULL CHECK (period IN ('hour','day','month','year')),

    effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_to   TIMESTAMPTZ,                  -- NULL = still in force
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CHECK (effective_to IS NULL OR effective_to > effective_from),
    -- For an org-level policy the entity IS the org.
    CHECK (entity_type <> 'org' OR entity_id = org_id),

    -- No two policies for the same entity + period may overlap in time. This
    -- guarantees the violation scan always finds AT MOST ONE governing policy,
    -- so it never has to resolve a tie.
    EXCLUDE USING GIST (
        entity_type WITH =,
        entity_id   WITH =,
        period      WITH =,
        tstzrange(effective_from, effective_to) WITH &&
    )
);

-- Serves the violation-scan join: entity_type =, entity_id =, period =,
-- followed by the effective-window range filter.
CREATE INDEX idx_emission_policies_lookup
    ON emission_policies (entity_type, entity_id, period);

-- Tenant scoping: "all policies for org X".
CREATE INDEX idx_emission_policies_org
    ON emission_policies (org_id);


-- ============================================================================
-- SECTION 5 -- ROLLUP TABLES
-- ============================================================================
-- A precomputed answer. One row = one bucket = "this entity, during this time
-- window, emitted this total". Time grain is implied by which table the row
-- lives in, so only bucket_start is stored (not bucket_end).
--
-- Three tables, split by grain. Sizing for ~1,100 entities (1,000 assets,
-- 100 sites, 1 org):
--   hourly  ~ 1,100 * 24 * 365 = ~9.6M rows/year   -> partitioned
--   daily   ~ 1,100 * 365      = ~400k rows/year    -> not partitioned
--   monthly ~ 1,100 * 12       = ~13k rows/year     -> not partitioned
-- Only the hourly table is large enough to justify partitioning.

CREATE TABLE emission_rollup_hourly (
    entity_type    TEXT        NOT NULL CHECK (entity_type IN ('org','site','asset')),
    entity_id      UUID        NOT NULL,
    bucket_start   TIMESTAMPTZ NOT NULL,            -- truncated to the hour
    total_emission NUMERIC     NOT NULL,            -- SUM of readings in bucket
    reading_count  INTEGER     NOT NULL,
    min_reading    NUMERIC     NOT NULL,            -- smallest single reading
    max_reading    NUMERIC     NOT NULL,            -- largest single reading
    unit           TEXT        NOT NULL DEFAULT 'kg_co2e',
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- PK enforces one bucket per entity per window, is the upsert conflict
    -- target, AND serves the dominant read (a trend for one entity over a
    -- time range) via its left prefix. bucket_start must be in the PK because
    -- it is the partition key.
    PRIMARY KEY (entity_type, entity_id, bucket_start)
) PARTITION BY RANGE (bucket_start);

CREATE TABLE emission_rollup_hourly_2026_05 PARTITION OF emission_rollup_hourly
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE emission_rollup_hourly_2026_06 PARTITION OF emission_rollup_hourly
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE emission_rollup_hourly_2026_07 PARTITION OF emission_rollup_hourly
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

-- Daily and monthly: column-for-column identical, not partitioned.
CREATE TABLE emission_rollup_daily (
    entity_type    TEXT        NOT NULL CHECK (entity_type IN ('org','site','asset')),
    entity_id      UUID        NOT NULL,
    bucket_start   TIMESTAMPTZ NOT NULL,            -- truncated to the day
    total_emission NUMERIC     NOT NULL,
    reading_count  INTEGER     NOT NULL,
    min_reading    NUMERIC     NOT NULL,
    max_reading    NUMERIC     NOT NULL,
    unit           TEXT        NOT NULL DEFAULT 'kg_co2e',
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (entity_type, entity_id, bucket_start)
);

CREATE TABLE emission_rollup_monthly (
    entity_type    TEXT        NOT NULL CHECK (entity_type IN ('org','site','asset')),
    entity_id      UUID        NOT NULL,
    bucket_start   TIMESTAMPTZ NOT NULL,            -- truncated to first-of-month
    total_emission NUMERIC     NOT NULL,
    reading_count  INTEGER     NOT NULL,
    min_reading    NUMERIC     NOT NULL,
    max_reading    NUMERIC     NOT NULL,
    unit           TEXT        NOT NULL DEFAULT 'kg_co2e',
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (entity_type, entity_id, bucket_start)
);


-- ============================================================================
-- SECTION 6 -- VIOLATIONS
-- ============================================================================
-- A violation is a machine-written observation: a rollup bucket exceeded its
-- governing policy. ONE row per (entity, policy, period bucket) -- upserted,
-- so the every-few-minutes scan never piles up duplicate rows for one breach.

CREATE TABLE emission_violations (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id            UUID        NOT NULL REFERENCES organizations(id),

    entity_type       TEXT        NOT NULL CHECK (entity_type IN ('org','site','asset')),
    entity_id         UUID        NOT NULL,

    policy_id         UUID        NOT NULL REFERENCES emission_policies(id),

    -- Snapshot of the policy at detection time. Frozen: retiring or editing
    -- the policy later never rewrites a violation's history.
    period            TEXT        NOT NULL,         -- grain, from policy.period
    limit_value       NUMERIC     NOT NULL,         -- from policy.emission_limit
    unit              TEXT        NOT NULL,         -- from policy.unit

    period_start      TIMESTAMPTZ NOT NULL,         -- the breached bucket's start
    measured_value    NUMERIC     NOT NULL,         -- the bucket's total_emission
    overage           NUMERIC     GENERATED ALWAYS AS (measured_value - limit_value) STORED,

    detected_at       TIMESTAMPTZ NOT NULL DEFAULT now(),   -- first breach (frozen)
    last_evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now(),   -- most recent re-check
    acknowledged_at   TIMESTAMPTZ,                          -- NULL = open

    -- One violation per breached bucket -- the upsert conflict target.
    UNIQUE (entity_type, entity_id, policy_id, period_start)
);

-- The alert dashboard: "open violations for org X, newest first". Partial
-- index keeps the working set to just unacknowledged rows.
CREATE INDEX idx_emission_violations_open
    ON emission_violations (org_id, detected_at DESC)
    WHERE acknowledged_at IS NULL;

-- Drill-down: full violation history for one entity.
CREATE INDEX idx_emission_violations_entity
    ON emission_violations (entity_type, entity_id, detected_at DESC);


-- ============================================================================
-- SECTION 7 -- THE JOB:  refresh_emissions(window)
-- ============================================================================
--
-- HOW THE ROLLUPS WORK
--   Both axes are summing hierarchies: a site = sum of its assets; an org =
--   sum of its sites; a day = sum of 24 hours; a month = sum of its days.
--   So there is ONE base computation (asset-hourly, from raw readings) and
--   every other bucket is derived by summing the level below. The cascade
--   runs in strict dependency order; raw readings are scanned exactly once.
--
--   The job is STATELESS and IDEMPOTENT. It recomputes a trailing `p_window`
--   of buckets every run. Because field engineers sync data with up to a 24h
--   delay, the hourly run uses a 48h window (24h delay + 24h safety margin).
--   The recorded_at filter prunes to recent partitions. Every write is an
--   upsert, so re-running -- or two runs overlapping -- is harmless.
--
-- HOW POLICY EVALUATION WORKS (Stage 2)
--   For each rollup bucket in the window, find its governing policy by
--   matching on three things: (1) entity, (2) grain -- the policy's `period`
--   equals the rollup table's grain, (3) time -- the policy was in effect at
--   the bucket's START (effective_from <= bucket_start < effective_to).
--   The bucket_start rule means a mid-period policy change takes effect at the
--   NEXT period boundary. If total_emission > emission_limit, upsert a
--   violation: first detection inserts; later runs only bump measured_value
--   and last_evaluated_at -- detected_at and the policy snapshot stay frozen.
--
-- +goose StatementBegin
CREATE OR REPLACE PROCEDURE refresh_emissions(p_window INTERVAL DEFAULT INTERVAL '48 hours')
LANGUAGE plpgsql
AS $$
BEGIN
    -- ===================== STAGE 1 -- ROLLUP CASCADE ========================

    -- Step 1: asset-hourly, from raw readings. The ONLY step that scans the
    -- readings table; the recorded_at filter prunes to recent partitions.
    INSERT INTO emission_rollup_hourly
        (entity_type, entity_id, bucket_start, total_emission,
         reading_count, min_reading, max_reading, unit, computed_at)
    SELECT 'asset', asset_id, date_trunc('hour', recorded_at),
           SUM(reading), COUNT(*), MIN(reading), MAX(reading), 'kg_co2e', now()
    FROM asset_emission_readings
    WHERE recorded_at >= date_trunc('hour', now()) - p_window
    GROUP BY asset_id, date_trunc('hour', recorded_at)
    ON CONFLICT (entity_type, entity_id, bucket_start) DO UPDATE SET
        total_emission = EXCLUDED.total_emission,
        reading_count  = EXCLUDED.reading_count,
        min_reading    = EXCLUDED.min_reading,
        max_reading    = EXCLUDED.max_reading,
        computed_at    = EXCLUDED.computed_at;

    -- Step 2: site-hourly, summing the asset-hourly rows from step 1.
    -- total/count are summed; min/max take MIN-of-mins / MAX-of-maxes.
    INSERT INTO emission_rollup_hourly
        (entity_type, entity_id, bucket_start, total_emission,
         reading_count, min_reading, max_reading, unit, computed_at)
    SELECT 'site', a.site_id, h.bucket_start,
           SUM(h.total_emission), SUM(h.reading_count),
           MIN(h.min_reading), MAX(h.max_reading), 'kg_co2e', now()
    FROM emission_rollup_hourly h
    JOIN assets a ON a.id = h.entity_id
    WHERE h.entity_type = 'asset'
      AND h.bucket_start >= date_trunc('hour', now()) - p_window
    GROUP BY a.site_id, h.bucket_start
    ON CONFLICT (entity_type, entity_id, bucket_start) DO UPDATE SET
        total_emission = EXCLUDED.total_emission,
        reading_count  = EXCLUDED.reading_count,
        min_reading    = EXCLUDED.min_reading,
        max_reading    = EXCLUDED.max_reading,
        computed_at    = EXCLUDED.computed_at;

    -- Step 3: org-hourly, summing the site-hourly rows from step 2.
    INSERT INTO emission_rollup_hourly
        (entity_type, entity_id, bucket_start, total_emission,
         reading_count, min_reading, max_reading, unit, computed_at)
    SELECT 'org', s.org_id, h.bucket_start,
           SUM(h.total_emission), SUM(h.reading_count),
           MIN(h.min_reading), MAX(h.max_reading), 'kg_co2e', now()
    FROM emission_rollup_hourly h
    JOIN sites s ON s.id = h.entity_id
    WHERE h.entity_type = 'site'
      AND h.bucket_start >= date_trunc('hour', now()) - p_window
    GROUP BY s.org_id, h.bucket_start
    ON CONFLICT (entity_type, entity_id, bucket_start) DO UPDATE SET
        total_emission = EXCLUDED.total_emission,
        reading_count  = EXCLUDED.reading_count,
        min_reading    = EXCLUDED.min_reading,
        max_reading    = EXCLUDED.max_reading,
        computed_at    = EXCLUDED.computed_at;

    -- Step 4: daily, all three entity levels at once (hourly already holds
    -- asset/site/org rows -- grouping by entity_type rolls them all up).
    INSERT INTO emission_rollup_daily
        (entity_type, entity_id, bucket_start, total_emission,
         reading_count, min_reading, max_reading, unit, computed_at)
    SELECT entity_type, entity_id, date_trunc('day', bucket_start),
           SUM(total_emission), SUM(reading_count),
           MIN(min_reading), MAX(max_reading), 'kg_co2e', now()
    FROM emission_rollup_hourly
    WHERE bucket_start >= date_trunc('day', now() - p_window)
    GROUP BY entity_type, entity_id, date_trunc('day', bucket_start)
    ON CONFLICT (entity_type, entity_id, bucket_start) DO UPDATE SET
        total_emission = EXCLUDED.total_emission,
        reading_count  = EXCLUDED.reading_count,
        min_reading    = EXCLUDED.min_reading,
        max_reading    = EXCLUDED.max_reading,
        computed_at    = EXCLUDED.computed_at;

    -- Step 5: monthly, all three entity levels, from daily.
    INSERT INTO emission_rollup_monthly
        (entity_type, entity_id, bucket_start, total_emission,
         reading_count, min_reading, max_reading, unit, computed_at)
    SELECT entity_type, entity_id, date_trunc('month', bucket_start),
           SUM(total_emission), SUM(reading_count),
           MIN(min_reading), MAX(max_reading), 'kg_co2e', now()
    FROM emission_rollup_daily
    WHERE bucket_start >= date_trunc('month', now() - p_window)
    GROUP BY entity_type, entity_id, date_trunc('month', bucket_start)
    ON CONFLICT (entity_type, entity_id, bucket_start) DO UPDATE SET
        total_emission = EXCLUDED.total_emission,
        reading_count  = EXCLUDED.reading_count,
        min_reading    = EXCLUDED.min_reading,
        max_reading    = EXCLUDED.max_reading,
        computed_at    = EXCLUDED.computed_at;

    -- ===================== STAGE 2 -- VIOLATION SCAN ========================
    -- One pass per grain. The JOIN encodes policy matching: entity + grain +
    -- in-effect-at-bucket_start. Only breaching buckets produce rows.

    -- Hourly grain
    INSERT INTO emission_violations
        (org_id, entity_type, entity_id, policy_id, period,
         limit_value, unit, period_start, measured_value,
         detected_at, last_evaluated_at)
    SELECT p.org_id, r.entity_type, r.entity_id, p.id, p.period,
           p.emission_limit, p.unit, r.bucket_start, r.total_emission, now(), now()
    FROM emission_rollup_hourly r
    JOIN emission_policies p
      ON  p.entity_type = r.entity_type
      AND p.entity_id   = r.entity_id
      AND p.period      = 'hour'
      AND p.effective_from <= r.bucket_start
      AND (p.effective_to IS NULL OR p.effective_to > r.bucket_start)
    WHERE r.bucket_start >= date_trunc('hour', now()) - p_window
      AND r.total_emission > p.emission_limit
    ON CONFLICT (entity_type, entity_id, policy_id, period_start) DO UPDATE SET
        measured_value    = EXCLUDED.measured_value,
        last_evaluated_at = EXCLUDED.last_evaluated_at;

    -- Daily grain
    INSERT INTO emission_violations
        (org_id, entity_type, entity_id, policy_id, period,
         limit_value, unit, period_start, measured_value,
         detected_at, last_evaluated_at)
    SELECT p.org_id, r.entity_type, r.entity_id, p.id, p.period,
           p.emission_limit, p.unit, r.bucket_start, r.total_emission, now(), now()
    FROM emission_rollup_daily r
    JOIN emission_policies p
      ON  p.entity_type = r.entity_type
      AND p.entity_id   = r.entity_id
      AND p.period      = 'day'
      AND p.effective_from <= r.bucket_start
      AND (p.effective_to IS NULL OR p.effective_to > r.bucket_start)
    WHERE r.bucket_start >= date_trunc('day', now() - p_window)
      AND r.total_emission > p.emission_limit
    ON CONFLICT (entity_type, entity_id, policy_id, period_start) DO UPDATE SET
        measured_value    = EXCLUDED.measured_value,
        last_evaluated_at = EXCLUDED.last_evaluated_at;

    -- Monthly grain
    INSERT INTO emission_violations
        (org_id, entity_type, entity_id, policy_id, period,
         limit_value, unit, period_start, measured_value,
         detected_at, last_evaluated_at)
    SELECT p.org_id, r.entity_type, r.entity_id, p.id, p.period,
           p.emission_limit, p.unit, r.bucket_start, r.total_emission, now(), now()
    FROM emission_rollup_monthly r
    JOIN emission_policies p
      ON  p.entity_type = r.entity_type
      AND p.entity_id   = r.entity_id
      AND p.period      = 'month'
      AND p.effective_from <= r.bucket_start
      AND (p.effective_to IS NULL OR p.effective_to > r.bucket_start)
    WHERE r.bucket_start >= date_trunc('month', now() - p_window)
      AND r.total_emission > p.emission_limit
    ON CONFLICT (entity_type, entity_id, policy_id, period_start) DO UPDATE SET
        measured_value    = EXCLUDED.measured_value,
        last_evaluated_at = EXCLUDED.last_evaluated_at;

    -- NOTE: period = 'year' policies are NOT checked -- there is no yearly
    -- rollup table. Either add emission_rollup_yearly + a 4th pass, or sum the
    -- 12 monthly buckets. Left as a deliberate, documented gap.

    RAISE NOTICE 'refresh_emissions: completed (window = %)', p_window;
END;
$$;
-- +goose StatementEnd


-- ============================================================================
-- SECTION 8 -- READ-SIDE VIEWS  &  QUERY TEMPLATES
-- ============================================================================
-- Why we use emission_rollup_MONTHLY:
--   * It is the smallest rollup table (~13k rows/year, whole platform), so even
--     summing an entity's entire history touches only a handful of rows.
--   * The current month's bucket already contains everything rolled up so far
--     this month -- so a sum of monthly buckets is correct "to date" without
--     adding daily/hourly buckets on top (that would double-count).
--   * It already holds org/site/asset rows, so any entity level is a direct
--     lookup -- an org total needs no summing of its assets.
 
 
-- LIFETIME total emitted, per entity, from the beginning of time through now.
-- This is "total emission till date" -- a pure cumulative figure, independent
-- of any policy or period window.
CREATE VIEW emission_total_to_date AS
SELECT entity_type,
       entity_id,
       SUM(total_emission)  AS total_to_date,
       SUM(reading_count)   AS reading_count,
       MAX(computed_at)     AS as_of
FROM emission_rollup_monthly
GROUP BY entity_type, entity_id;
-- Usage:  SELECT * FROM emission_total_to_date
--         WHERE entity_type = $1 AND entity_id = $2;

-- Query templates (application-side):
--
--   Trend for one entity (pick the rollup table matching the grain):
--     SELECT bucket_start, total_emission, min_reading, max_reading
--     FROM   emission_rollup_daily
--     WHERE  entity_type = $1 AND entity_id = $2
--       AND  bucket_start >= $3 AND bucket_start < $4
--     ORDER  BY bucket_start;
--
--   Open violations for an org (alert dashboard):
--     SELECT * FROM emission_violations
--     WHERE  org_id = $1 AND acknowledged_at IS NULL
--     ORDER  BY detected_at DESC;
--
--   Acknowledge a violation:
--     UPDATE emission_violations SET acknowledged_at = now() WHERE id = $1;



-- +goose Down

-- Views
DROP VIEW IF EXISTS emission_total_to_date;

-- Stored procedure
DROP PROCEDURE IF EXISTS refresh_emissions;

-- Violations
DROP TABLE IF EXISTS emission_violations;

-- Rollup tables
DROP TABLE IF EXISTS emission_rollup_monthly;
DROP TABLE IF EXISTS emission_rollup_daily;
DROP TABLE IF EXISTS emission_rollup_hourly;

-- Policies
DROP TABLE IF EXISTS emission_policies;

-- Readings (partitioned -- parent cascades to children)
DROP TABLE IF EXISTS asset_emission_readings;

-- People & devices
DROP TABLE IF EXISTS user_recorder_devices;
DROP TABLE IF EXISTS recorder_devices;
DROP TABLE IF EXISTS users;

-- Core hierarchy (reverse dependency order)
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS asset_types;
DROP TABLE IF EXISTS organizations;

DROP EXTENSION IF EXISTS btree_gist;
